# Library name
NAME = ovvcdec
DESC = OpenVVC decoder library

# List of library headers to be installed
HEADERS = ovvcdec.h                                                   \

# List of objects to be included into the library
OBJS = ovvcdec.o                                                      \
       ovunits.o                                                      \

