# Library name
NAME = ovvcdec
DESC = OpenVVC decoder library

# List of library headers to be installed
HEADERS = ovvcdec.h                                                   \
					rcn_fill_ref.h																							\
					rcn_intra_dc_planar.h																				\
					data_rcn_transform.h																				\
					rcn_transform.h																							\
					rcn_intra_angular.h																					\
					rcn_lfnst.h																									\
					rcn_mc.h																										\

# List of objects to be included into the library
OBJS = ovvcdec.o                                                      \
       ovunits.o                                                      \
			 rcn_fill_ref.o																									\
			 rcn_intra_dc_planar.o																					\
			 data_rcn_transform.o																						\
			 rcn_transform.o																								\
			 rcn_intra_angular.o																						\
			 rcn_lfnst.o																										\
			 rcn_mc.o																												\
