# Library name
NAME = ovvcdmx
DESC = OpenVVC demuxing library

# List of library headers to be installed
HEADERS = ovvcdmx.h                                                   \

# List of objects to be included into the library
OBJS = ovvcdmx.o                                                      \
       ovio.o                                                         \

