# Library name
NAME = ovvcutils
DESC = OpenVVC utilitary library

# List of library headers to be installed
HEADERS = ovvcutils.h                                                 \
					ovvcerror.h																									\

# List of objects to be included into the library
OBJS = ovvcutils.o                                                    \
       ovmem.o                                                        \
			 ovvcerror.o																										\
